cloud:
  eureka-host: localhost:8761
banks:
  private: "https://api.privatbank.ua/p24api/exchange_rates?json"
  monoBank: "https://api.monobank.ua/bank/currency"
server:
  port: 8085
client:
  config:
    privateBankUrl: "https://api.privatbank.ua/p24api/exchange_rates?json"
    monoBankUrl: "https://api.monobank.ua/bank/currency"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}/eureka/
    enabled: true
spring:
  application:
    name: currency-service
