server:
  port: 8090
spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5433/processing
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db
    url: jdbc:postgresql://localhost:5433/processing
    user: postgres
    password: pass
  application:
    name: processing-service

service:
  currency:
    url: "http://localhost:8085/currency"


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true